### ISSUE TITLE
[Feature] html/react 使用优化

### ISSUE THREAD

**Issue by xile611** [VisActor/VRender#1128]
### What problem does this feature solve?

![img_v3_029j_d2b78448-7df6-47d8-9623-0e9406c4c32g](https://github.com/VisActor/VRender/assets/6111424/0b8f0ac0-6fe3-4bfa-b406-0b3da3b7fe26)

### What does the proposed API look like?

* VRnder工作： html属性优化
  * 图形节点支持 forceWidth、forceHeight 
  * 事件支持：forceWidth、forceHeight 能够被pick到，支持事件（pickMode: 'imprecise'）
  * 主图元的属性能够转换到html上
    * text
      * font相关属性
      * fill 转 color
      * textAlign
      * textBaseline
      * underline
      * lineThrough
       * lineHeight
    * 其他图元的，读取theme中的text配置

<img width="479" alt="image" src="https://github.com/VisActor/VRender/assets/6111424/51a32191-be38-4ac1-ae03-4551f33fa998">

**Comment by neuqzxy** [comment]
26日之前VRender提供

**Comment by xile611** [comment]
vchart issue:  https://github.com/VisActor/VChart/issues/1150

**Comment by xile611** [comment]
https://github.com/VisActor/VRender/pull/1159
