### ISSUE TITLE
[Bug] `connectedType` of line works error when has defined: false point

### ISSUE THREAD

**Issue by xile611** [VisActor/VRender#1492]
### Version

no

### Link to Minimal Reproduction

no need

### Steps to Reproduce

https://github.com/VisActor/VChart/issues/3238
66ec09a4e905a400f7326a2a

### Current Behavior

no

### Expected Behavior

no

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
closed by https://github.com/VisActor/VRender/pull/1588

**Comment by neuqzxy** [comment]
63bd232d9d831755c006901c
