### ISSUE TITLE
[Bug] vrender render error when support scroll

### ISSUE THREAD

**Issue by xile611** [VisActor/VRender#1535]
### Version

no

### Link to Minimal Reproduction

no

### Steps to Reproduce

todo

### Current Behavior

接入滚动条后，渲染出错

### Expected Behavior

正常渲染

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
closed by https://github.com/VisActor/VRender/pull/1593
