### ISSUE TITLE
The underline and strikethrough colors of text do not follow the color of text.

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VRender#21]
![Image](https://user-images.githubusercontent.com/135952300/244988046-77b76518-f57f-48c9-9a4c-d9081c108978.png)

The underline and strikethrough colors of text do not follow the color of text，you can see this link: https://bugserver.cn.goofy.app/photo?product=chartspace4&version=1.0.0.285&reportid=6482f586802d7ba8ff6151b4

**Comment by neuqzxy** [comment]
fixed in commit 499355fa888c850827d07a64afac94d14f014907
