### ISSUE TITLE
[Bug] array stroke effect in arc graphic is not correct

### ISSUE THREAD

**Issue by xiaoluoHe** [VisActor/VRender#454]
### Version

0.14.0

### Link to Minimal Reproduction

none

### Steps to Reproduce

const graphics = [];
graphics.push(VRender.createArc({
  innerRadius: 0,
  outerRadius: 120,
  startAngle: 0,
  endAngle: Math.PI * 0.75,
  x: 200,
  y: 200,
  fill: 'pink',
  // stroke: ['green', false, false, false], // correct
  stroke: [false, 'green', 'green', 'green'], // not as expected
  lineWidth: 2,
}));

const stage = new Stage({
  container: CONTAINER_ID,
  autoRender: true
});

graphics.forEach(g => {
  stage.defaultLayer.add(g);
})

### Current Behavior

![image](https://github.com/VisActor/VRender/assets/11360419/2890d28b-84d2-4fc5-bc80-187e3759c1a6)

### Expected Behavior

![image](https://github.com/VisActor/VRender/assets/11360419/9c656d09-0977-46f4-8de8-7a67cd6f6aa6)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
fixed in https://github.com/VisActor/VRender/pull/489
