### ISSUE TITLE
[Bug] The gradient color does not render correctly

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VRender#71]
### Version

0.10.3

### Link to Minimal Reproduction

none

### Steps to Reproduce

1. radial gradient, see: https://jsfiddle.net/74anm0hu/
2. linear gradient, see: https://jsfiddle.net/upb7oe0w/
3. 环形渐变：https://jsfiddle.net/hqyb85Lz/

### Current Behavior

see the picture diff:

![image](https://github.com/VisActor/VRender/assets/135952300/09dfc103-8575-4a17-b5c4-c1a4d9b20316)
![image](https://github.com/VisActor/VRender/assets/135952300/01abfc84-4d29-4012-9951-f7c68249330f)
![image](https://github.com/VisActor/VRender/assets/135952300/87807504-83b6-4576-b361-5095f62979b9)
![image](https://github.com/VisActor/VRender/assets/135952300/f74c3c7d-54b9-4dfc-a64f-b2f66a814fa0)
![image](https://github.com/VisActor/VRender/assets/135952300/db335971-f7ef-44d1-ac4d-92ada790d498)

### Expected Behavior

render as the standard picture

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
fixed on https://github.com/VisActor/VRender/pull/75
