### ISSUE TITLE
[Feature]  add api docs

### ISSUE THREAD

**Issue by millievn** [VisActor/VRender#751]
### What problem does this feature solve?

api docs not available

<img width="1116" alt="image" src="https://github.com/VisActor/VRender/assets/37304367/801a14a5-cb30-473c-b8df-74e9a9dd6ec3">

### What does the proposed API look like?

- show how to get cursor position when double click
- show how to append text at cursor

**Comment by neuqzxy** [comment]
https://visactor.io/vrender/option/Arc
