### ISSUE TITLE
[Feature] 多个坐标轴支持对齐

### ISSUE THREAD

**Issue by Rui-Sun** [VisActor/VRender#857]
### What problem does this feature solve?

![img_v3_026o_d0925bae-e21b-468d-93f1-b960822a0bbg](https://github.com/VisActor/VRender/assets/25134429/431cad55-fc21-4b3d-abd8-14268ea5ca4f)
坐标轴组件支持估计宽度，不同label长度title可以对齐

### What does the proposed API look like?

![img_v3_026o_705ce685-b592-471f-a760-173668b5bfbg](https://github.com/VisActor/VRender/assets/25134429/6ccb0cb0-0660-410c-beb2-58234018439f)

**Comment by xile611** [comment]
可以通过 设置属性 `verticalLimitSize` 和 `verticalMinSize` 为相同的值实现该效果
<img width="431" alt="image" src="https://github.com/VisActor/VRender/assets/6111424/526af74a-0e49-47d0-a400-349e54af29b4">
