### ISSUE TITLE
[Feature] arc mark supports `innerPadding` and `outerPadding`

### ISSUE THREAD

**Issue by zamhown** [VisActor/VRender#897]
### What problem does this feature solve?

在 vchart 中，进度图的 padding 和 radius 需要分别配置且支持状态和更新动画

### What does the proposed API look like?

{
  innerPadding: number // 单位：px
  outerPadding: number // 单位：px
}

**Comment by neuqzxy** [comment]
https://github.com/VisActor/VRender/pull/950
