### ISSUE TITLE
[Bug] VGroup在不设置width属性的时候，添加fill或者background属性不生效，且VGroup里有多个Vtext元素时，在不添加width属性时，VGroup属性不能自适应

### ISSUE THREAD

**Issue by Wal1e** [VisActor/VRender#912]
### Version

0.17.12-alpha.1

### Link to Minimal Reproduction

-1

### Steps to Reproduce

前置条件： VGroup未添加width属性，因为场景是期待被里面的元素撑起自适应
1、设置fill或者background属性不生效

### Current Behavior

前置条件： VGroup未添加width属性，因为场景是期待被里面的元素撑起自适应
1、设置fill或者background属性不生效

### Expected Behavior

前置条件： VGroup未添加width属性，因为场景是期待被里面的元素撑起自适应
1、设置fill或者background属性生效、
2、VGroup的width在不设置时，支持自适应功能

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
1. 我们将支持不配置width和height时绘制background的功能
2. 对于VGroup属性不自适应的问题：VRender不会主动去修改attribute中的属性，如果需要获取VGroup包含子元素后的宽高，可以通过group的AABBBounds属性获取
