### ISSUE TITLE
[Bug] FadeInPlus animate will generate wrong graident color

### ISSUE THREAD

**Issue by xile611** [VisActor/VRender#96]
### Version

0.11.1

### Link to Minimal Reproduction

todo

### Steps to Reproduce

todo

### Current Behavior

<img width="497" alt="image" src="https://github.com/VisActor/VRender/assets/6111424/454b01a5-40cc-43e0-b70c-dd1081d17d0c">

<img width="1061" alt="image" src="https://github.com/VisActor/VRender/assets/6111424/e7bde9af-ffde-46fb-b951-3f27152129da">

### Expected Behavior

no error should be throw

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by neuqzxy** [comment]
这个color不支持false，渐变色里step的color属性没有默认值，必须是字符串 @xile611
